### ISSUE TITLE
Partner Stewards

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#112] opened 2016-05-19 20:55 UTC
Enspiral Members don't have stewards which means if there is conflict or tension there is quite a high barrier for anyone who has an issue with a member to raise it. Often when there is conflict or tension the other party is overloaded and doesn't have the energy to reach a resolution or convene a discussion so the problem goes overlooked.

If each Enspiral Member had a formal steward then it might increase the amount of feedback and highlight issues that need resolving faster.

**Comment by ahdinosaur** [comment] 2016-05-23 02:22
duplicate of https://github.com/enspiral/improvements/issues/91?

**Closed** 2016-09-02 05:34 UTC
